# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ejOsjariV5adb-P7iOV4lthKfqARFbLN
"""

nome = input("Qual... é o seu nome? ")
print('Benvindo', nome)